### ISSUE TITLE
Personal file url in dev

### ISSUE THREAD

**Issue by tdatkinson** [revabam/bambam-client#104]
A url pointing to a file on Richards computer made it to dev. It needs to be removed - Chinedu

Path:  bambam-client/src/styles.css

`#bg{
    background-image: url("C:/Users/Richard/Desktop/background_pictures/amaterasu.jpg");
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-position: center; 
    background-size: cover; 
}`

**Comment by ChineduOzodi** [comment]
Has been removed from dev
